vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO winsoft666/WinCrashpad
    HEAD_REF master
    REF 7b5f7df0043299738349d8efd7a206f5e16ec9a4
    SHA512 0
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" WINCRASHPAD_BUILD_SHARED_LIBS)
string(COMPARE EQUAL "${VCPKG_CRT_LINKAGE}" "static" WINCRASHPAD_USE_STATIC_CRT)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        -DWINCRASHPAD_BUILD_SHARED_LIBS:BOOL=${WINCRASHPAD_BUILD_SHARED_LIBS}
        -DWINCRASHPAD_USE_STATIC_CRT:BOOL=${WINCRASHPAD_USE_STATIC_CRT}
        -DWINCRASHPAD_BUILD_DEMOS=OFF
)

vcpkg_install_cmake()

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)

vcpkg_copy_pdbs()
